### ISSUE TITLE
Controlling the "loading" animation via constructor variable

### ISSUE THREAD

**Issue by Drabuna** [jiangyang5157/flutter_progress_button#3]
Hi,

Nice widget - would be really useful to be able to chose:

1. Star showing progressWidget onPressed (current behaviour)
2. Be able to start showing progressWidget via some sort of flag, so can be controled via parent state.

Something like
`
ProgressButton(
 showProgress: true/false
)
`

**Comment by joaquini** [comment]
Any update on this?
